#ifndef FLASH_KERNEL_API_H_
#define FLASH_KERNEL_API_H_

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define FLASH_KERNEL_ABI_VERSION 1u

typedef enum FlashStatusCode {
  FLASH_STATUS_OK = 0,
  FLASH_STATUS_INVALID_ARGUMENT = 1,
  FLASH_STATUS_UNSUPPORTED = 2,
  FLASH_STATUS_UNAVAILABLE = 3,
  FLASH_STATUS_INTERNAL = 4,
} FlashStatusCode;

typedef enum FlashDataType {
  FLASH_DTYPE_INVALID = 0,
  FLASH_DTYPE_BF16 = 1,
  FLASH_DTYPE_NVFP4_E2M1_PACKED = 2,
  FLASH_DTYPE_FP8_E4M3 = 3,
  FLASH_DTYPE_F32 = 4,
  FLASH_DTYPE_INT32 = 5,
} FlashDataType;

typedef enum FlashScaleLayout {
  FLASH_SCALE_LAYOUT_INVALID = 0,
  FLASH_SCALE_LAYOUT_LINEAR = 1,
  // FlashInfer/CUTLASS block-scale layout: padded rows are split into groups
  // of 128 and scale columns into groups of 4 before MMA-order permutation.
  FLASH_SCALE_LAYOUT_CUTLASS_128X4 = 2,
} FlashScaleLayout;

typedef enum FlashKernelBackend {
  FLASH_BACKEND_AUTO = 0,
  FLASH_BACKEND_FLASHINFER_MM_FP4 = 1,
  FLASH_BACKEND_CUTLASS_SM121 = 2,
  // FlashInfer's grouped SM120/121 NVFP4 GEMM. Flash owns routing and
  // token permutation; the donor kernel owns only the tensor-core matmul.
  FLASH_BACKEND_FLASHINFER_GROUP_MM_FP4 = 3,
  // FlashInfer CuTe-DSL fused SiLU/multiply/NVFP4 quantizer. Its exported
  // artifact is consumed without Python, PyTorch, or SGLang at serving time.
  FLASH_BACKEND_FLASHINFER_CUTE_SILU_NVFP4 = 4,
  // FlashInfer CuTe-DSL BF16 -> NVFP4 quantizer exported for Qwen K=2560.
  FLASH_BACKEND_FLASHINFER_CUTE_NVFP4_QUANTIZE = 5,
  // Row gather and weighted finalize adapted from FlashInfer's fused-MoE
  // prologue/epilogue. Rust owns the maps and scheduling policy.
  FLASH_BACKEND_FLASHINFER_MOE_ROUTE = 6,
  // FP8 PLE row gather matching SGLang's Qwen4 pinned-host Triton arithmetic.
  FLASH_BACKEND_SGLANG_PLE_GATHER = 7,
  // Radix-select QSA block top-k adapted from SGLang's JIT CUDA kernel.
  FLASH_BACKEND_SGLANG_QSA_TOPK = 8,
  // Fused QSA Q/K norm, RoPE, state-store, and compressed-K preparation.
  FLASH_BACKEND_SGLANG_QSA_INDEX_PREP = 9,
  // QSA valid-count and selected-K/V compaction adapted from SGLang's Triton
  // sparse-attention path. Rust owns the page-aligned output layout.
  FLASH_BACKEND_SGLANG_QSA_KV_PACK = 10,
  // FlashInfer XQA BF16 paged decode specialized to Qwen QSA on SM121.
  FLASH_BACKEND_FLASHINFER_XQA_DECODE = 11,
  // Fixed-width compressed-block to logical-token expansion adapted from
  // SGLang's QSA Triton kernel.
  FLASH_BACKEND_SGLANG_QSA_EXPAND = 12,
  // SGLang QSA decode score generated by pinned TileLang MMA templates.
  FLASH_BACKEND_TILELANG_QSA_SCORE = 13,
  // Qwen router projection through cuBLAS followed by SGLang's workspace-free
  // 512-expert softmax/top-k kernel. Rust owns the handle, stream, buffers,
  // route-map construction, and expert scheduling.
  FLASH_BACKEND_SGLANG_CUBLAS_MOE_GATE = 14,
  // Qwen BF16 shared expert: cuBLAS projections plus SGLang-compatible
  // SiLU/multiply and sigmoid broadcast kernels.
  FLASH_BACKEND_SGLANG_CUBLAS_SHARED_EXPERT = 15,
  // SGLang's deployed Qwen CUDA epilogue: FP32 gate dot/sigmoid, shared
  // multiply, and in-place add into the routed BF16 output.
  FLASH_BACKEND_SGLANG_FUSED_MOE_JOIN = 16,
  // Qwen mHC: SGLang grouped Gemma RMSNorm/combine arithmetic with cuBLAS
  // low-rank projections and a deterministic fused mix epilogue.
  FLASH_BACKEND_SGLANG_CUBLAS_MHC = 17,
  // Qwen GDN half-layer framing: cuBLAS projections, the pinned
  // SGLang/causal-conv1d update, and SGLang FLA gated RMSNorm. The recurrent
  // FlashInfer GDN remains a separate stage so Rust owns state scheduling.
  FLASH_BACKEND_SGLANG_CUBLAS_GDN_BLOCK = 18,
} FlashKernelBackend;

typedef enum FlashGdnBackend {
  FLASH_GDN_BACKEND_AUTO = 0,
  // Flash-owned correctness-first CUDA decode kernel. It implements the
  // same BF16-state recurrence used by the pinned FlashInfer/SGLang oracle.
  FLASH_GDN_BACKEND_LOCAL_CUDA = 1,
  // Pinned FlashInfer CuTe BF16-state artifact exported offline for SM121 and
  // called through TVM-FFI without Python, Torch, SGLang, or serving-time JIT.
  FLASH_GDN_BACKEND_FLASHINFER = 2,
} FlashGdnBackend;

typedef enum FlashSharedExpertOutputMode {
  // Legacy isolated branch: materialize sigmoid(shared_gate) * shared output.
  FLASH_SHARED_EXPERT_OUTPUT_GATED = 0,
  // Production path: leave the down projection ungated for the borrowed
  // fused gate/sigmoid/multiply/add epilogue.
  FLASH_SHARED_EXPERT_OUTPUT_UNGATED = 1,
} FlashSharedExpertOutputMode;

typedef struct FlashStatus {
  int32_t code;
  const char* message;
} FlashStatus;

typedef struct FlashDeviceCaps {
  uint32_t struct_size;
  uint32_t abi_version;
  // CUDA compute capability encoded as major * 10 + minor: GB10 is 121.
  uint32_t sm;
  uint32_t supports_fp4_tensor_cores;
  uint64_t workspace_limit_bytes;
} FlashDeviceCaps;

// Logical operation shape plus the padded shape consumed by native FP4 MMA.
// The adapter owns any backend-specific transpose; callers always describe
// input [M,K], weight [N,K], and output [M,N].
typedef struct FlashDenseNvfp4Plan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint64_t m;
  uint64_t n;
  uint64_t k;
  uint64_t padded_n;
  uint64_t padded_k;
  // Weight block-scale rows have a stricter FlashInfer/CUTLASS alignment
  // than packed weight rows and therefore have their own physical extent.
  uint64_t scale_padded_n;
  uint32_t group_size;
  uint32_t input_scale_layout;
  uint32_t weight_scale_layout;
  uint32_t output_dtype;
  uint32_t requested_backend;
  uint32_t reserved;
} FlashDenseNvfp4Plan;

typedef struct FlashNvfp4MatrixView {
  // Two E2M1 values are packed into each byte.
  const void* packed_data;
  // One FP8-E4M3 scale for every group_size logical values.
  const void* block_scales;
  uint64_t packed_row_stride_bytes;
  uint64_t scale_row_stride_bytes;
} FlashNvfp4MatrixView;

typedef struct FlashDenseNvfp4Args {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashDenseNvfp4Plan plan;
  FlashNvfp4MatrixView input;
  FlashNvfp4MatrixView weight;
  void* output;
  uint64_t output_row_stride_bytes;
  // Matches SGLang ModelOpt: input_global_scale * weight_global_scale.
  float alpha;
  uint32_t reserved;
  void* workspace;
  uint64_t workspace_bytes;
  // Opaque cudaStream_t. No CUDA header crosses the stable ABI.
  void* cuda_stream;
  // GPU-addressable copy of alpha. The runtime allocates these immutable
  // scalars with the model so FlashInfer can dereference them inside GEMM and
  // CUDA graph capture never performs a host-to-device scalar copy.
  const float* alpha_device;
} FlashDenseNvfp4Args;

// Grouped expert projection over already-routed rows. The scheduler supplies
// `num_groups + 1` device INT32 offsets. Every group length is padded to a
// multiple of four, as required by the pinned FlashInfer kernel.
typedef struct FlashGroupedNvfp4Plan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_groups;
  uint32_t group_size;
  uint64_t total_rows;
  uint64_t input_scale_rows;
  uint64_t n;
  uint64_t k;
  uint32_t tile_m;
  uint32_t tile_n;
  uint32_t tile_k;
  uint32_t swap_ab;
  uint32_t input_scale_layout;
  uint32_t weight_scale_layout;
  uint32_t output_dtype;
  uint32_t requested_backend;
} FlashGroupedNvfp4Plan;

typedef struct FlashGroupedNvfp4WeightView {
  // Packed E2M1: [num_groups,N,K/2].
  const void* packed_data;
  // FP8-E4M3, CUTLASS 128x4: [num_groups,N,K/16].
  const void* block_scales;
  uint64_t packed_group_stride_bytes;
  uint64_t scale_group_stride_bytes;
} FlashGroupedNvfp4WeightView;

typedef struct FlashGroupedNvfp4Args {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashGroupedNvfp4Plan plan;
  // Packed routed activations [total_rows,K/2]. Scale rows include the
  // per-expert 128-row physical padding described by input_scale_rows.
  FlashNvfp4MatrixView input;
  FlashGroupedNvfp4WeightView weights;
  // Device INT32 [num_groups+1], starting at zero and ending at total_rows.
  const int32_t* m_indptr;
  // Device FP32 [num_groups].
  const float* alpha_device;
  void* output;
  uint64_t output_row_stride_bytes;
  void* int_workspace;
  uint64_t int_workspace_bytes;
  void* float_workspace;
  uint64_t float_workspace_bytes;
  void* cuda_stream;
} FlashGroupedNvfp4Args;

// Sparse logical-expert view over an immutable, strided expert store. The
// nested grouped arguments retain compact routed activations, m_indptr, output,
// workspaces, and alpha[num_groups]. `logical_group_ids` is the CUDA-visible
// compact-group -> source-group map consumed by the FlashInfer argument
// preparer. With reserved=0 its host mirror is validation-only and must contain
// identical INT32 values for the duration of launch submission. With
// reserved=1, device IDs are produced dynamically by an earlier same-stream
// kernel and the host array is only a valid unique shape/range witness.
typedef struct FlashIndexedGroupedNvfp4Args {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashGroupedNvfp4Args grouped;
  const int32_t* logical_group_ids;
  const int32_t* logical_group_ids_host;
  uint32_t source_group_count;
  uint32_t reserved;  // 0=mirrored IDs, 1=device-selected IDs
} FlashIndexedGroupedNvfp4Args;

// Expert-major fused activation and requantization between the two MoE GEMMs.
// Input is BF16 [E,M,2K] in [gate,up] order. Output is packed E2M1
// [E,M,K/2], plus one CUTLASS 128x4 scale tile per expert. `active_rows`
// is a host array that masks unused capacity; a later scheduler-owned
// compaction step forms the variable-row grouped-GEMM input without copying
// model weights. Scales remain device-resident and may vary by expert.
typedef struct FlashSiluNvfp4Plan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_experts;
  uint32_t rows_per_expert;
  uint64_t hidden_size;
  uint32_t group_size;
  uint32_t input_dtype;
  uint32_t output_scale_layout;
  uint32_t requested_backend;
  uint32_t reserved;
} FlashSiluNvfp4Plan;

typedef struct FlashSiluNvfp4Args {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashSiluNvfp4Plan plan;
  const void* input;
  const float* input_global_scales;
  const int32_t* active_rows;
  void* packed_output;
  void* output_scales;
  uint64_t input_expert_stride_bytes;
  uint64_t output_expert_stride_bytes;
  uint64_t scale_expert_stride_bytes;
  void* cuda_stream;
} FlashSiluNvfp4Args;

// In-place-friendly form for the grouped MoE pipeline. `input` is the compact
// BF16 output of grouped GEMM1 and `packed_output` is the compact input for
// grouped GEMM2. Rust supplies host-resident row metadata from the same
// GroupedExpertLayout used to build m_indptr; no activation or weight copy is
// needed between the borrowed kernels.
typedef struct FlashSegmentedSiluNvfp4Plan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_experts;
  uint32_t group_size;
  uint64_t total_rows;
  uint64_t input_scale_rows;
  uint64_t hidden_size;
  uint32_t input_dtype;
  uint32_t output_scale_layout;
  uint32_t requested_backend;
  uint32_t reserved;
} FlashSegmentedSiluNvfp4Plan;

typedef struct FlashSegmentedSiluNvfp4Args {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashSegmentedSiluNvfp4Plan plan;
  const void* input;
  const float* input_global_scales;
  const int32_t* active_rows_host;
  const int32_t* m_indptr_host;
  const uint64_t* scale_row_offsets_host;
  void* packed_output;
  void* output_scales;
  uint64_t input_row_stride_bytes;
  uint64_t output_row_stride_bytes;
  uint64_t scale_row_stride_bytes;
  void* cuda_stream;
} FlashSegmentedSiluNvfp4Args;

// Segmented BF16 -> NVFP4 input quantization for grouped GEMM1. The row and
// scale offsets are the same scheduler-owned layout used by the two grouped
// GEMMs. The linked donor object is specialized for Qwen's K=2560.
typedef struct FlashSegmentedNvfp4QuantizePlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_experts;
  uint32_t group_size;
  uint64_t total_rows;
  uint64_t input_scale_rows;
  uint64_t hidden_size;
  uint32_t input_dtype;
  uint32_t output_scale_layout;
  uint32_t requested_backend;
  uint32_t reserved;
} FlashSegmentedNvfp4QuantizePlan;

typedef struct FlashSegmentedNvfp4QuantizeArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashSegmentedNvfp4QuantizePlan plan;
  const void* input;
  const float* input_global_scales;
  const int32_t* active_rows_host;
  const int32_t* m_indptr_host;
  const uint64_t* scale_row_offsets_host;
  void* packed_output;
  void* output_scales;
  uint64_t input_row_stride_bytes;
  uint64_t output_row_stride_bytes;
  uint64_t scale_row_stride_bytes;
  void* cuda_stream;
} FlashSegmentedNvfp4QuantizeArgs;

// Scheduler-owned MoE row permutation. Natural route order is
// token-major: route = token * top_k + rank. `route_to_packed_row` is a
// device UINT32 array generated from the Rust RoutePlan. Padding rows are
// cleared during dispatch and ignored during finalize.
typedef struct FlashMoeRoutePlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_tokens;
  uint32_t top_k;
  uint32_t num_experts;
  uint32_t reserved;
  uint64_t hidden_size;
  uint64_t total_rows;
} FlashMoeRoutePlan;

typedef struct FlashMoeRouteArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashMoeRoutePlan plan;
  const void* token_input;
  const uint32_t* route_to_packed_row;
  void* packed_input;
  const float* route_weights;
  const void* packed_expert_output;
  void* token_output;
  uint64_t token_input_row_stride_bytes;
  uint64_t packed_row_stride_bytes;
  uint64_t expert_output_row_stride_bytes;
  void* cuda_stream;
} FlashMoeRouteArgs;

// Qwen3.8 Flash-Next's complete routed-expert selection boundary. The router
// is a compact BF16 matrix [512,2560]. Logits remain in the caller's fixed
// coherent arena so the two borrowed operations can be captured without an
// allocator or a framework runtime.
typedef struct FlashMoeGatePlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_tokens;
  uint32_t hidden_size;
  uint32_t num_experts;
  uint32_t top_k;
  uint32_t input_dtype;
  uint32_t weight_dtype;
  uint32_t logits_dtype;
  uint32_t requested_backend;
  uint32_t renormalize;
  uint32_t reserved;
} FlashMoeGatePlan;

typedef struct FlashMoeGateArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashMoeGatePlan plan;
  // BF16 [num_tokens,hidden_size].
  const void* hidden_states;
  // BF16 [num_experts,hidden_size], row-major.
  const void* router_weight;
  // BF16 [num_tokens,num_experts], row-major fixed scratch/output.
  void* router_logits;
  // FP32 and INT32 [num_tokens,top_k].
  float* topk_weights;
  int32_t* topk_ids;
  // Raw cublasHandle_t owned by Rust's FlashCudaBlas owner.
  void* cublas_handle;
  void* cuda_stream;
} FlashMoeGateArgs;

typedef struct FlashSharedExpertPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_tokens;
  uint32_t hidden_size;
  uint32_t intermediate_size;
  uint32_t input_dtype;
  uint32_t weight_dtype;
  uint32_t output_dtype;
  uint32_t requested_backend;
  uint32_t output_mode;
  uint32_t reserved1;
  uint32_t reserved2;
} FlashSharedExpertPlan;

typedef struct FlashSharedExpertArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashSharedExpertPlan plan;
  const void* hidden_states;
  // BF16 [2*intermediate,hidden] in SGLang merged gate/up order. The loader
  // reads the two checkpoint slices directly into this final resident region.
  const void* gate_up_weight;
  const void* down_weight;
  const void* shared_gate_weight;
  // Fixed BF16 scratch: [tokens,2*intermediate], [tokens,intermediate],
  // and [tokens,1].
  void* gate_up;
  void* activated;
  void* shared_gate;
  // BF16 [tokens,hidden]. GATED mode applies sigmoid(shared_gate); UNGATED
  // mode leaves the down projection ready for flash_moe_join_launch.
  void* output;
  void* cublas_handle;
  void* cuda_stream;
} FlashSharedExpertArgs;

typedef struct FlashMoeJoinPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_tokens;
  uint32_t hidden_size;
  uint32_t input_dtype;
  uint32_t output_dtype;
  uint32_t requested_backend;
  uint32_t reserved;
} FlashMoeJoinPlan;

typedef struct FlashMoeJoinArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashMoeJoinPlan plan;
  // BF16 [tokens,hidden], BF16 [hidden], and BF16 [tokens,hidden].
  const void* hidden_states;
  const void* shared_gate_weight;
  const void* shared_output;
  // BF16 [tokens,hidden], updated in place with
  // routed + sigmoid(dot(hidden, gate_weight)) * shared.
  void* routed_output;
  void* cuda_stream;
} FlashMoeJoinArgs;

typedef struct FlashMhcPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_tokens;
  uint32_t hc_count;
  uint32_t hidden_size;
  uint32_t lowrank_size;
  uint32_t dtype;
  uint32_t requested_backend;
  float rms_norm_eps;
  uint32_t reserved0;
  uint32_t reserved1;
  uint32_t reserved2;
} FlashMhcPlan;

typedef struct FlashMhcArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashMhcPlan plan;
  // BF16 resident input/weights.
  const void* hyper_input;
  const void* norm_weight;
  const void* mix_down_weight;
  const void* mix_up_weight;
  const void* inject_weight;
  const void* block_output;
  // Fixed BF16 scratch and outputs.
  void* normed;
  void* mix_down;
  void* mix_activated;
  void* mix_up;
  void* mixed_output;
  void* combined_output;
  void* cublas_handle;
  void* cuda_stream;
} FlashMhcArgs;

// One logical FP8 PLE row may cross two fixed cache pages. Rust uploads these
// compact descriptors into preallocated device scratch; both offsets are
// relative to the stable coherent-slab device base.
typedef struct FlashPleRowFragment {
  uint64_t first_offset_bytes;
  uint64_t second_offset_bytes;
  uint32_t first_bytes;
  uint32_t second_bytes;
} FlashPleRowFragment;

typedef struct FlashPleGatherPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t rows;
  uint32_t row_bytes;
  uint32_t input_dtype;
  uint32_t output_dtype;
  uint32_t requested_backend;
  uint32_t reserved;
} FlashPleGatherPlan;

typedef struct FlashPleGatherArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashPleGatherPlan plan;
  const void* coherent_base;
  // Device array [rows]. Every descriptor must cover exactly row_bytes.
  const FlashPleRowFragment* fragments;
  // BF16 [rows,row_bytes].
  void* output;
  uint64_t output_row_stride_bytes;
  // Raw BF16 bits. Qwen3.8 Flash-Next uses 0x3951.
  uint16_t scale_bf16_bits;
  uint16_t reserved16;
  uint32_t reserved32;
  void* cuda_stream;
} FlashPleGatherArgs;

typedef struct FlashQsaTopkPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t rows;
  uint32_t columns;
  uint32_t topk;
  uint32_t input_dtype;
  uint32_t output_dtype;
  uint32_t requested_backend;
  // FP32 elements between score rows; must be at least columns.
  uint64_t input_stride;
} FlashQsaTopkPlan;

typedef struct FlashQsaTopkArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashQsaTopkPlan plan;
  const float* scores;
  // Device int32 [rows]. Indices are relative to each row start.
  const int32_t* row_starts;
  // Device int32 [rows]. Every start + length must be <= columns.
  const int32_t* lengths;
  // Device int32 [rows,topk]. Order is intentionally unspecified.
  int32_t* indices;
  void* cuda_stream;
} FlashQsaTopkArgs;

typedef struct FlashQsaExpandPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t rows;
  uint32_t block_topk;
  uint32_t compress_ratio;
  uint32_t token_topk;
  uint32_t final_topk;
  uint32_t output_dtype;
  uint32_t requested_backend;
  uint32_t reserved;
} FlashQsaExpandPlan;

typedef struct FlashQsaExpandArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashQsaExpandPlan plan;
  // INT32 [rows,block_topk]. Valid block ids precede -1 padding.
  const int32_t* block_indices;
  // INT64 [rows] and INT32 [rows].
  const int64_t* query_positions;
  const int32_t* sequence_lengths;
  // INT32 [rows,final_topk]. Valid logical ids precede -1 padding.
  int32_t* logical_indices;
  void* cuda_stream;
} FlashQsaExpandArgs;

typedef struct FlashQsaScorePlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t batch_size;
  uint32_t pages;
  uint32_t max_pages;
  uint32_t max_model_len;
  uint32_t query_heads;
  uint32_t head_dim;
  uint32_t page_size;
  uint32_t query_dtype;
  uint32_t logits_dtype;
  uint32_t requested_backend;
} FlashQsaScorePlan;

typedef struct FlashQsaScoreArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashQsaScorePlan plan;
  // BF16 [batch_size,query_heads,head_dim]. Heads 4..7 are zero padding.
  const void* query;
  // BF16 [pages,page_size,1,head_dim].
  const void* key_cache;
  // INT32 [batch_size,max_pages] and INT32 [batch_size].
  const int32_t* page_table;
  const int32_t* context_lengths;
  // FP32 [batch_size,max_model_len]. Only positions below context length are
  // written; the immediately following top-k stage consumes the same lengths.
  float* logits;
  float score_scale;
  uint32_t reserved;
  void* cuda_stream;
} FlashQsaScoreArgs;

typedef struct FlashQsaIndexPrepPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t tokens;
  uint32_t groups;
  uint32_t state_slots;
  uint32_t compressed_slots;
  uint32_t num_q_heads;
  uint32_t head_dim;
  uint32_t rotary_dim;
  uint32_t compress_ratio;
  uint32_t num_position_axes;
  uint32_t dtype;
  uint32_t requested_backend;
  uint32_t q_heads_padded;
} FlashQsaIndexPrepPlan;

typedef struct FlashQsaIndexPrepArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashQsaIndexPrepPlan plan;
  // BF16 [tokens,(num_q_heads+1),head_dim].
  const void* qk;
  // BF16 [tokens,q_heads_padded,head_dim]. Heads >= num_q_heads are zero.
  void* q_output;
  const void* q_norm_weight;
  const void* k_norm_weight;
  // FP32 [cos_sin_rows,rotary_dim].
  const float* cos_sin_cache;
  uint64_t cos_sin_rows;
  const int32_t* axis_map;
  // INT64 [num_position_axes,tokens], with an explicit row stride.
  const int64_t* positions;
  uint64_t positions_stride;
  const int64_t* cache_locs;
  // Persistent BF16 [state_slots,head_dim].
  void* key_state;
  // Persistent INT64 [state_slots,3].
  int64_t* rope_positions;
  // INT32 [groups,compress_ratio] and [groups]. Null when groups == 0.
  const int32_t* group_locs;
  const int32_t* write_locs;
  // Persistent BF16 [compressed_slots,head_dim].
  void* compressed_keys;
  float eps;
  uint32_t reserved;
  void* cuda_stream;
} FlashQsaIndexPrepArgs;

typedef struct FlashQsaKvPackPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t batch_size;
  uint32_t slot_capacity;
  uint32_t request_capacity;
  // INT32 elements between rows of req_to_token.
  uint32_t request_stride;
  // Final pooled QSA/DSA selection width: 2048 sparse positions plus three
  // tail positions. Invalid tail entries must follow the valid prefix.
  uint32_t topk;
  // Page-aligned destination stride. For page size 64 and topk 2051 this is
  // 2112 tokens, matching SGLang's TRT-LLM-gen path.
  uint32_t packed_row_stride;
  uint32_t num_kv_heads;
  uint32_t head_dim;
  uint32_t dtype;
  uint32_t requested_backend;
} FlashQsaKvPackPlan;

typedef struct FlashQsaKvPackArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashQsaKvPackPlan plan;
  // BF16 persistent K/V state: [slot_capacity,num_kv_heads,head_dim].
  const void* key_state;
  const void* value_state;
  // INT32 [request_capacity,request_stride].
  const int32_t* req_to_token;
  // INT32 [batch_size].
  const int32_t* request_indices;
  // INT32 [batch_size,topk]. Valid entries occupy a contiguous prefix.
  const int32_t* logical_indices;
  const int32_t* sequence_lengths;
  // INT32 [batch_size], consumed directly as TRT-LLM-gen seq_lens.
  int32_t* valid_counts;
  // BF16 [batch_size,packed_row_stride,num_kv_heads,head_dim].
  void* packed_key;
  void* packed_value;
  void* cuda_stream;
} FlashQsaKvPackArgs;

typedef struct FlashQsaDecodePlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t batch_size;
  uint32_t multiprocessor_count;
  uint32_t num_q_heads;
  uint32_t num_kv_heads;
  uint32_t head_dim;
  uint32_t page_size;
  uint32_t pages_per_row;
  uint32_t packed_row_stride;
  uint32_t dtype;
  uint32_t requested_backend;
  uint32_t enable_pdl;
  uint32_t reserved;
} FlashQsaDecodePlan;

typedef struct FlashQsaDecodeArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashQsaDecodePlan plan;
  // BF16 [batch_size,num_q_heads,head_dim].
  const void* query;
  // BF16 NHD scratch, viewed as
  // [batch_size*pages_per_row,page_size,num_kv_heads,head_dim].
  const void* packed_key;
  const void* packed_value;
  // INT32 [batch_size,pages_per_row] and [batch_size].
  const int32_t* block_tables;
  const int32_t* sequence_lengths;
  // BF16 [batch_size,num_q_heads,head_dim].
  void* output;
  // Zero-initialize once before first use. XQA reserves its first 8 MiB for
  // semaphores and uses the remainder as fixed scratch.
  void* workspace;
  uint64_t workspace_bytes;
  float bmm1_scale;
  float bmm2_scale;
  void* cuda_stream;
} FlashQsaDecodeArgs;

typedef struct FlashKernelInfo {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t backend;
  uint32_t available;
  uint64_t workspace_bytes;
  const char* name;
  const char* source_revision;
} FlashKernelInfo;

// Gated Delta Network decode/short-prefill. Sequence length is fixed by an AOT
// bucket (1/2/4/8/16); longer prompts are decomposed by the Rust scheduler.
// The native implementation is fixed to the Qwen3.8 Flash shape K=V=128 and
// BF16 recurrent state. Q/K use H heads, V/state use HV heads.
typedef struct FlashGdnDecodePlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t batch_size;
  uint32_t num_qk_heads;
  uint32_t num_value_heads;
  uint32_t key_dim;
  uint32_t value_dim;
  uint32_t state_slots;
  uint32_t state_dtype;
  uint32_t requested_backend;
} FlashGdnDecodePlan;

typedef struct FlashGdnDecodeArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashGdnDecodePlan plan;
  // BF16 Q/K: [B,T,H,K]. BF16 V: [B,T,HV,V].
  const void* q;
  const void* k;
  const void* v;
  // BF16 input-dependent gates: [B,T,HV].
  const void* a;
  const void* b;
  // FP32 persistent gate parameters: [HV].
  const float* a_log;
  const float* dt_bias;
  // BF16 K-contiguous state pool: [slots,HV,V,K], updated in place.
  void* state_pool;
  // INT32 slot per batch row. A negative index produces zero output and no
  // state write. Active rows must name distinct slots within one launch.
  const int32_t* state_indices;
  // BF16 output: [B,T,HV,V].
  void* output;
  float scale;
  uint32_t sequence_length;
  void* cuda_stream;
} FlashGdnDecodeArgs;

// Stateless projection/epilogue framing around the stateful GDN recurrence.
// Rust deliberately launches prepare -> GDN recurrence -> finish as separate
// stages so it can checkpoint both recurrent pools and schedule each request.
typedef struct FlashGdnBlockPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_tokens;
  uint32_t hidden_size;
  uint32_t num_qk_heads;
  uint32_t num_value_heads;
  uint32_t head_dim;
  uint32_t conv_kernel;
  uint32_t dtype;
  uint32_t requested_backend;
  float rms_norm_eps;
  uint32_t reserved;
} FlashGdnBlockPlan;

typedef struct FlashGdnBlockArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  FlashGdnBlockPlan plan;
  // BF16 input and resident checkpoint weights.
  const void* hidden_states;
  const void* in_proj_qkv_weight;
  const void* in_proj_z_weight;
  const void* in_proj_b_weight;
  const void* in_proj_a_weight;
  const void* conv_weight;
  const void* gated_norm_weight;
  const void* out_proj_weight;
  // BF16 [slots,10240,3] rolling convolution state and INT32 [tokens] slots.
  void* conv_state_pool;
  const int32_t* state_indices;
  // Caller-owned fixed BF16 scratch. No serving-time allocation occurs.
  void* projected_qkv;
  void* projected_z;
  void* projected_b;
  void* projected_a;
  void* convolved_qkv;
  const void* gdn_core_output;
  void* gated_norm_output;
  void* attention_output;
  void* cublas_handle;
  void* cuda_stream;
} FlashGdnBlockArgs;

uint32_t flash_kernel_abi_version(void);

FlashStatus flash_dense_nvfp4_validate(
    const FlashDenseNvfp4Plan* plan);

// Query is safe before model allocation. A valid candidate may be returned
// with available=0 until its external CUDA backend is linked.
FlashStatus flash_dense_nvfp4_query(
    const FlashDeviceCaps* caps,
    const FlashDenseNvfp4Plan* plan,
    FlashKernelInfo* info);

FlashStatus flash_dense_nvfp4_launch(
    const FlashDeviceCaps* caps,
    const FlashDenseNvfp4Args* args);

FlashStatus flash_grouped_nvfp4_validate(
    const FlashGroupedNvfp4Plan* plan);

FlashStatus flash_grouped_nvfp4_query(
    const FlashDeviceCaps* caps,
    const FlashGroupedNvfp4Plan* plan,
    FlashKernelInfo* info);

FlashStatus flash_grouped_nvfp4_launch(
    const FlashDeviceCaps* caps,
    const FlashGroupedNvfp4Args* args);

FlashStatus flash_indexed_grouped_nvfp4_launch(
    const FlashDeviceCaps* caps,
    const FlashIndexedGroupedNvfp4Args* args);

FlashStatus flash_silu_nvfp4_validate(
    const FlashSiluNvfp4Plan* plan);

FlashStatus flash_silu_nvfp4_query(
    const FlashDeviceCaps* caps,
    const FlashSiluNvfp4Plan* plan,
    FlashKernelInfo* info);

FlashStatus flash_silu_nvfp4_launch(
    const FlashDeviceCaps* caps,
    const FlashSiluNvfp4Args* args);

FlashStatus flash_segmented_silu_nvfp4_validate(
    const FlashSegmentedSiluNvfp4Plan* plan);

FlashStatus flash_segmented_silu_nvfp4_query(
    const FlashDeviceCaps* caps,
    const FlashSegmentedSiluNvfp4Plan* plan,
    FlashKernelInfo* info);

FlashStatus flash_segmented_silu_nvfp4_launch(
    const FlashDeviceCaps* caps,
    const FlashSegmentedSiluNvfp4Args* args);

FlashStatus flash_segmented_nvfp4_quantize_validate(
    const FlashSegmentedNvfp4QuantizePlan* plan);

FlashStatus flash_segmented_nvfp4_quantize_query(
    const FlashDeviceCaps* caps,
    const FlashSegmentedNvfp4QuantizePlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_segmented_nvfp4_quantize_launch(
    const FlashDeviceCaps* caps,
    const FlashSegmentedNvfp4QuantizeArgs* args);

FlashStatus flash_moe_route_validate(
    const FlashMoeRoutePlan* plan);

FlashStatus flash_moe_route_query(
    const FlashDeviceCaps* caps,
    const FlashMoeRoutePlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_moe_route_dispatch(
    const FlashDeviceCaps* caps,
    const FlashMoeRouteArgs* args);

FlashStatus flash_moe_route_finalize(
    const FlashDeviceCaps* caps,
    const FlashMoeRouteArgs* args);

FlashStatus flash_moe_gate_validate(
    const FlashMoeGatePlan* plan);

FlashStatus flash_moe_gate_query(
    const FlashDeviceCaps* caps,
    const FlashMoeGatePlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_moe_gate_launch(
    const FlashDeviceCaps* caps,
    const FlashMoeGateArgs* args);

FlashStatus flash_shared_expert_validate(
    const FlashSharedExpertPlan* plan);

FlashStatus flash_shared_expert_query(
    const FlashDeviceCaps* caps,
    const FlashSharedExpertPlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_shared_expert_launch(
    const FlashDeviceCaps* caps,
    const FlashSharedExpertArgs* args);

FlashStatus flash_moe_join_validate(
    const FlashMoeJoinPlan* plan);

FlashStatus flash_moe_join_query(
    const FlashDeviceCaps* caps,
    const FlashMoeJoinPlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_moe_join_launch(
    const FlashDeviceCaps* caps,
    const FlashMoeJoinArgs* args);

FlashStatus flash_mhc_validate(
    const FlashMhcPlan* plan);

FlashStatus flash_mhc_query(
    const FlashDeviceCaps* caps,
    const FlashMhcPlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_mhc_mix_launch(
    const FlashDeviceCaps* caps,
    const FlashMhcArgs* args);

FlashStatus flash_mhc_combine_launch(
    const FlashDeviceCaps* caps,
    const FlashMhcArgs* args);

FlashStatus flash_ple_gather_validate(
    const FlashPleGatherPlan* plan);

FlashStatus flash_ple_gather_query(
    const FlashDeviceCaps* caps,
    const FlashPleGatherPlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_ple_gather_launch(
    const FlashDeviceCaps* caps,
    const FlashPleGatherArgs* args);

FlashStatus flash_qsa_topk_validate(
    const FlashQsaTopkPlan* plan);

FlashStatus flash_qsa_topk_query(
    const FlashDeviceCaps* caps,
    const FlashQsaTopkPlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_qsa_topk_launch(
    const FlashDeviceCaps* caps,
    const FlashQsaTopkArgs* args);

FlashStatus flash_qsa_expand_validate(
    const FlashQsaExpandPlan* plan);

FlashStatus flash_qsa_expand_query(
    const FlashDeviceCaps* caps,
    const FlashQsaExpandPlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_qsa_expand_launch(
    const FlashDeviceCaps* caps,
    const FlashQsaExpandArgs* args);

FlashStatus flash_qsa_score_validate(
    const FlashQsaScorePlan* plan);

FlashStatus flash_qsa_score_query(
    const FlashDeviceCaps* caps,
    const FlashQsaScorePlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_qsa_score_launch(
    const FlashDeviceCaps* caps,
    const FlashQsaScoreArgs* args);

FlashStatus flash_qsa_index_prep_validate(
    const FlashQsaIndexPrepPlan* plan);

FlashStatus flash_qsa_index_prep_query(
    const FlashDeviceCaps* caps,
    const FlashQsaIndexPrepPlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_qsa_index_prep_launch(
    const FlashDeviceCaps* caps,
    const FlashQsaIndexPrepArgs* args);

FlashStatus flash_qsa_kv_pack_validate(
    const FlashQsaKvPackPlan* plan);

FlashStatus flash_qsa_kv_pack_query(
    const FlashDeviceCaps* caps,
    const FlashQsaKvPackPlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_qsa_kv_pack_launch(
    const FlashDeviceCaps* caps,
    const FlashQsaKvPackArgs* args);

FlashStatus flash_qsa_decode_validate(
    const FlashQsaDecodePlan* plan);

FlashStatus flash_qsa_decode_query(
    const FlashDeviceCaps* caps,
    const FlashQsaDecodePlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_qsa_decode_launch(
    const FlashDeviceCaps* caps,
    const FlashQsaDecodeArgs* args);

FlashStatus flash_gdn_decode_validate(
    const FlashGdnDecodePlan* plan);

FlashStatus flash_gdn_decode_query(
    const FlashDeviceCaps* caps,
    const FlashGdnDecodePlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_gdn_decode_launch(
    const FlashDeviceCaps* caps,
    const FlashGdnDecodeArgs* args);

FlashStatus flash_gdn_block_validate(
    const FlashGdnBlockPlan* plan);

FlashStatus flash_gdn_block_query(
    const FlashDeviceCaps* caps,
    const FlashGdnBlockPlan* plan,
    FlashKernelInfo* info);

FlashStatus flash_gdn_block_prepare_launch(
    const FlashDeviceCaps* caps,
    const FlashGdnBlockArgs* args);

FlashStatus flash_gdn_block_finish_launch(
    const FlashDeviceCaps* caps,
    const FlashGdnBlockArgs* args);

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // FLASH_KERNEL_API_H_
