SHELL := /usr/bin/env bash

.PHONY: build download serve smoke bench stop

build:
	@./scripts/build.sh

download:
	@./scripts/download.sh

serve:
	@./scripts/serve.sh

smoke:
	@./scripts/smoke.sh

bench:
	@./scripts/bench.sh

stop:
	@./scripts/stop.sh
