#ifndef SPARKSERVE_KERNEL_API_H_
#define SPARKSERVE_KERNEL_API_H_

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SPARKSERVE_KERNEL_ABI_VERSION 1u

typedef enum SparkServeStatusCode {
  SPARKSERVE_STATUS_OK = 0,
  SPARKSERVE_STATUS_INVALID_ARGUMENT = 1,
  SPARKSERVE_STATUS_UNSUPPORTED = 2,
  SPARKSERVE_STATUS_UNAVAILABLE = 3,
  SPARKSERVE_STATUS_INTERNAL = 4,
} SparkServeStatusCode;

typedef enum SparkServeDataType {
  SPARKSERVE_DTYPE_INVALID = 0,
  SPARKSERVE_DTYPE_BF16 = 1,
  SPARKSERVE_DTYPE_NVFP4_E2M1_PACKED = 2,
  SPARKSERVE_DTYPE_FP8_E4M3 = 3,
  SPARKSERVE_DTYPE_F32 = 4,
  SPARKSERVE_DTYPE_INT32 = 5,
} SparkServeDataType;

typedef enum SparkServeScaleLayout {
  SPARKSERVE_SCALE_LAYOUT_INVALID = 0,
  SPARKSERVE_SCALE_LAYOUT_LINEAR = 1,
  // FlashInfer/CUTLASS block-scale layout: padded rows are split into groups
  // of 128 and scale columns into groups of 4 before MMA-order permutation.
  SPARKSERVE_SCALE_LAYOUT_CUTLASS_128X4 = 2,
} SparkServeScaleLayout;

typedef enum SparkServeKernelBackend {
  SPARKSERVE_BACKEND_AUTO = 0,
  SPARKSERVE_BACKEND_FLASHINFER_MM_FP4 = 1,
  SPARKSERVE_BACKEND_CUTLASS_SM121 = 2,
  // FlashInfer's grouped SM120/121 NVFP4 GEMM. SparkServe owns routing and
  // token permutation; the donor kernel owns only the tensor-core matmul.
  SPARKSERVE_BACKEND_FLASHINFER_GROUP_MM_FP4 = 3,
  // FlashInfer CuTe-DSL fused SiLU/multiply/NVFP4 quantizer. Its exported
  // artifact is consumed without Python, PyTorch, or SGLang at serving time.
  SPARKSERVE_BACKEND_FLASHINFER_CUTE_SILU_NVFP4 = 4,
  // FlashInfer CuTe-DSL BF16 -> NVFP4 quantizer exported for Qwen K=2560.
  SPARKSERVE_BACKEND_FLASHINFER_CUTE_NVFP4_QUANTIZE = 5,
  // Row gather and weighted finalize adapted from FlashInfer's fused-MoE
  // prologue/epilogue. Rust owns the maps and scheduling policy.
  SPARKSERVE_BACKEND_FLASHINFER_MOE_ROUTE = 6,
  // FP8 PLE row gather matching SGLang's Qwen4 pinned-host Triton arithmetic.
  SPARKSERVE_BACKEND_SGLANG_PLE_GATHER = 7,
  // Radix-select QSA block top-k adapted from SGLang's JIT CUDA kernel.
  SPARKSERVE_BACKEND_SGLANG_QSA_TOPK = 8,
  // Fused QSA Q/K norm, RoPE, state-store, and compressed-K preparation.
  SPARKSERVE_BACKEND_SGLANG_QSA_INDEX_PREP = 9,
  // QSA valid-count and selected-K/V compaction adapted from SGLang's Triton
  // sparse-attention path. Rust owns the page-aligned output layout.
  SPARKSERVE_BACKEND_SGLANG_QSA_KV_PACK = 10,
  // FlashInfer XQA BF16 paged decode specialized to Qwen QSA on SM121.
  SPARKSERVE_BACKEND_FLASHINFER_XQA_DECODE = 11,
  // Fixed-width compressed-block to logical-token expansion adapted from
  // SGLang's QSA Triton kernel.
  SPARKSERVE_BACKEND_SGLANG_QSA_EXPAND = 12,
  // SGLang QSA decode score generated by pinned TileLang MMA templates.
  SPARKSERVE_BACKEND_TILELANG_QSA_SCORE = 13,
} SparkServeKernelBackend;

typedef enum SparkServeGdnBackend {
  SPARKSERVE_GDN_BACKEND_AUTO = 0,
  // SparkServe-owned correctness-first CUDA decode kernel. It implements the
  // same BF16-state recurrence used by the pinned FlashInfer/SGLang oracle.
  SPARKSERVE_GDN_BACKEND_LOCAL_CUDA = 1,
  // Reserved for a future raw FlashInfer adapter. The current FlashInfer GDN
  // entry point is Python/CuTe DSL and is not linked into the shipping runtime.
  SPARKSERVE_GDN_BACKEND_FLASHINFER = 2,
} SparkServeGdnBackend;

typedef struct SparkServeStatus {
  int32_t code;
  const char* message;
} SparkServeStatus;

typedef struct SparkServeDeviceCaps {
  uint32_t struct_size;
  uint32_t abi_version;
  // CUDA compute capability encoded as major * 10 + minor: GB10 is 121.
  uint32_t sm;
  uint32_t supports_fp4_tensor_cores;
  uint64_t workspace_limit_bytes;
} SparkServeDeviceCaps;

// Logical operation shape plus the padded shape consumed by native FP4 MMA.
// The adapter owns any backend-specific transpose; callers always describe
// input [M,K], weight [N,K], and output [M,N].
typedef struct SparkServeDenseNvfp4Plan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint64_t m;
  uint64_t n;
  uint64_t k;
  uint64_t padded_n;
  uint64_t padded_k;
  // Weight block-scale rows have a stricter FlashInfer/CUTLASS alignment
  // than packed weight rows and therefore have their own physical extent.
  uint64_t scale_padded_n;
  uint32_t group_size;
  uint32_t input_scale_layout;
  uint32_t weight_scale_layout;
  uint32_t output_dtype;
  uint32_t requested_backend;
  uint32_t reserved;
} SparkServeDenseNvfp4Plan;

typedef struct SparkServeNvfp4MatrixView {
  // Two E2M1 values are packed into each byte.
  const void* packed_data;
  // One FP8-E4M3 scale for every group_size logical values.
  const void* block_scales;
  uint64_t packed_row_stride_bytes;
  uint64_t scale_row_stride_bytes;
} SparkServeNvfp4MatrixView;

typedef struct SparkServeDenseNvfp4Args {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeDenseNvfp4Plan plan;
  SparkServeNvfp4MatrixView input;
  SparkServeNvfp4MatrixView weight;
  void* output;
  uint64_t output_row_stride_bytes;
  // Matches SGLang ModelOpt: input_global_scale * weight_global_scale.
  float alpha;
  uint32_t reserved;
  void* workspace;
  uint64_t workspace_bytes;
  // Opaque cudaStream_t. No CUDA header crosses the stable ABI.
  void* cuda_stream;
  // GPU-addressable copy of alpha. The runtime allocates these immutable
  // scalars with the model so FlashInfer can dereference them inside GEMM and
  // CUDA graph capture never performs a host-to-device scalar copy.
  const float* alpha_device;
} SparkServeDenseNvfp4Args;

// Grouped expert projection over already-routed rows. The scheduler supplies
// `num_groups + 1` device INT32 offsets. Every group length is padded to a
// multiple of four, as required by the pinned FlashInfer kernel.
typedef struct SparkServeGroupedNvfp4Plan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_groups;
  uint32_t group_size;
  uint64_t total_rows;
  uint64_t input_scale_rows;
  uint64_t n;
  uint64_t k;
  uint32_t tile_m;
  uint32_t tile_n;
  uint32_t tile_k;
  uint32_t swap_ab;
  uint32_t input_scale_layout;
  uint32_t weight_scale_layout;
  uint32_t output_dtype;
  uint32_t requested_backend;
} SparkServeGroupedNvfp4Plan;

typedef struct SparkServeGroupedNvfp4WeightView {
  // Packed E2M1: [num_groups,N,K/2].
  const void* packed_data;
  // FP8-E4M3, CUTLASS 128x4: [num_groups,N,K/16].
  const void* block_scales;
  uint64_t packed_group_stride_bytes;
  uint64_t scale_group_stride_bytes;
} SparkServeGroupedNvfp4WeightView;

typedef struct SparkServeGroupedNvfp4Args {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeGroupedNvfp4Plan plan;
  // Packed routed activations [total_rows,K/2]. Scale rows include the
  // per-expert 128-row physical padding described by input_scale_rows.
  SparkServeNvfp4MatrixView input;
  SparkServeGroupedNvfp4WeightView weights;
  // Device INT32 [num_groups+1], starting at zero and ending at total_rows.
  const int32_t* m_indptr;
  // Device FP32 [num_groups].
  const float* alpha_device;
  void* output;
  uint64_t output_row_stride_bytes;
  void* int_workspace;
  uint64_t int_workspace_bytes;
  void* float_workspace;
  uint64_t float_workspace_bytes;
  void* cuda_stream;
} SparkServeGroupedNvfp4Args;

// Expert-major fused activation and requantization between the two MoE GEMMs.
// Input is BF16 [E,M,2K] in [gate,up] order. Output is packed E2M1
// [E,M,K/2], plus one CUTLASS 128x4 scale tile per expert. `active_rows`
// is a host array that masks unused capacity; a later scheduler-owned
// compaction step forms the variable-row grouped-GEMM input without copying
// model weights. Scales remain device-resident and may vary by expert.
typedef struct SparkServeSiluNvfp4Plan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_experts;
  uint32_t rows_per_expert;
  uint64_t hidden_size;
  uint32_t group_size;
  uint32_t input_dtype;
  uint32_t output_scale_layout;
  uint32_t requested_backend;
  uint32_t reserved;
} SparkServeSiluNvfp4Plan;

typedef struct SparkServeSiluNvfp4Args {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeSiluNvfp4Plan plan;
  const void* input;
  const float* input_global_scales;
  const int32_t* active_rows;
  void* packed_output;
  void* output_scales;
  uint64_t input_expert_stride_bytes;
  uint64_t output_expert_stride_bytes;
  uint64_t scale_expert_stride_bytes;
  void* cuda_stream;
} SparkServeSiluNvfp4Args;

// In-place-friendly form for the grouped MoE pipeline. `input` is the compact
// BF16 output of grouped GEMM1 and `packed_output` is the compact input for
// grouped GEMM2. Rust supplies host-resident row metadata from the same
// GroupedExpertLayout used to build m_indptr; no activation or weight copy is
// needed between the borrowed kernels.
typedef struct SparkServeSegmentedSiluNvfp4Plan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_experts;
  uint32_t group_size;
  uint64_t total_rows;
  uint64_t input_scale_rows;
  uint64_t hidden_size;
  uint32_t input_dtype;
  uint32_t output_scale_layout;
  uint32_t requested_backend;
  uint32_t reserved;
} SparkServeSegmentedSiluNvfp4Plan;

typedef struct SparkServeSegmentedSiluNvfp4Args {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeSegmentedSiluNvfp4Plan plan;
  const void* input;
  const float* input_global_scales;
  const int32_t* active_rows_host;
  const int32_t* m_indptr_host;
  const uint64_t* scale_row_offsets_host;
  void* packed_output;
  void* output_scales;
  uint64_t input_row_stride_bytes;
  uint64_t output_row_stride_bytes;
  uint64_t scale_row_stride_bytes;
  void* cuda_stream;
} SparkServeSegmentedSiluNvfp4Args;

// Segmented BF16 -> NVFP4 input quantization for grouped GEMM1. The row and
// scale offsets are the same scheduler-owned layout used by the two grouped
// GEMMs. The linked donor object is specialized for Qwen's K=2560.
typedef struct SparkServeSegmentedNvfp4QuantizePlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_experts;
  uint32_t group_size;
  uint64_t total_rows;
  uint64_t input_scale_rows;
  uint64_t hidden_size;
  uint32_t input_dtype;
  uint32_t output_scale_layout;
  uint32_t requested_backend;
  uint32_t reserved;
} SparkServeSegmentedNvfp4QuantizePlan;

typedef struct SparkServeSegmentedNvfp4QuantizeArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeSegmentedNvfp4QuantizePlan plan;
  const void* input;
  const float* input_global_scales;
  const int32_t* active_rows_host;
  const int32_t* m_indptr_host;
  const uint64_t* scale_row_offsets_host;
  void* packed_output;
  void* output_scales;
  uint64_t input_row_stride_bytes;
  uint64_t output_row_stride_bytes;
  uint64_t scale_row_stride_bytes;
  void* cuda_stream;
} SparkServeSegmentedNvfp4QuantizeArgs;

// Scheduler-owned MoE row permutation. Natural route order is
// token-major: route = token * top_k + rank. `route_to_packed_row` is a
// device UINT32 array generated from the Rust RoutePlan. Padding rows are
// cleared during dispatch and ignored during finalize.
typedef struct SparkServeMoeRoutePlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t num_tokens;
  uint32_t top_k;
  uint32_t num_experts;
  uint32_t reserved;
  uint64_t hidden_size;
  uint64_t total_rows;
} SparkServeMoeRoutePlan;

typedef struct SparkServeMoeRouteArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeMoeRoutePlan plan;
  const void* token_input;
  const uint32_t* route_to_packed_row;
  void* packed_input;
  const float* route_weights;
  const void* packed_expert_output;
  void* token_output;
  uint64_t token_input_row_stride_bytes;
  uint64_t packed_row_stride_bytes;
  uint64_t expert_output_row_stride_bytes;
  void* cuda_stream;
} SparkServeMoeRouteArgs;

// One logical FP8 PLE row may cross two fixed cache pages. Rust uploads these
// compact descriptors into preallocated device scratch; both offsets are
// relative to the stable coherent-slab device base.
typedef struct SparkServePleRowFragment {
  uint64_t first_offset_bytes;
  uint64_t second_offset_bytes;
  uint32_t first_bytes;
  uint32_t second_bytes;
} SparkServePleRowFragment;

typedef struct SparkServePleGatherPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t rows;
  uint32_t row_bytes;
  uint32_t input_dtype;
  uint32_t output_dtype;
  uint32_t requested_backend;
  uint32_t reserved;
} SparkServePleGatherPlan;

typedef struct SparkServePleGatherArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServePleGatherPlan plan;
  const void* coherent_base;
  // Device array [rows]. Every descriptor must cover exactly row_bytes.
  const SparkServePleRowFragment* fragments;
  // BF16 [rows,row_bytes].
  void* output;
  uint64_t output_row_stride_bytes;
  // Raw BF16 bits. Qwen3.8 Flash-Next uses 0x3951.
  uint16_t scale_bf16_bits;
  uint16_t reserved16;
  uint32_t reserved32;
  void* cuda_stream;
} SparkServePleGatherArgs;

typedef struct SparkServeQsaTopkPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t rows;
  uint32_t columns;
  uint32_t topk;
  uint32_t input_dtype;
  uint32_t output_dtype;
  uint32_t requested_backend;
  // FP32 elements between score rows; must be at least columns.
  uint64_t input_stride;
} SparkServeQsaTopkPlan;

typedef struct SparkServeQsaTopkArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeQsaTopkPlan plan;
  const float* scores;
  // Device int32 [rows]. Indices are relative to each row start.
  const int32_t* row_starts;
  // Device int32 [rows]. Every start + length must be <= columns.
  const int32_t* lengths;
  // Device int32 [rows,topk]. Order is intentionally unspecified.
  int32_t* indices;
  void* cuda_stream;
} SparkServeQsaTopkArgs;

typedef struct SparkServeQsaExpandPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t rows;
  uint32_t block_topk;
  uint32_t compress_ratio;
  uint32_t token_topk;
  uint32_t final_topk;
  uint32_t output_dtype;
  uint32_t requested_backend;
  uint32_t reserved;
} SparkServeQsaExpandPlan;

typedef struct SparkServeQsaExpandArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeQsaExpandPlan plan;
  // INT32 [rows,block_topk]. Valid block ids precede -1 padding.
  const int32_t* block_indices;
  // INT64 [rows] and INT32 [rows].
  const int64_t* query_positions;
  const int32_t* sequence_lengths;
  // INT32 [rows,final_topk]. Valid logical ids precede -1 padding.
  int32_t* logical_indices;
  void* cuda_stream;
} SparkServeQsaExpandArgs;

typedef struct SparkServeQsaScorePlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t batch_size;
  uint32_t pages;
  uint32_t max_pages;
  uint32_t max_model_len;
  uint32_t query_heads;
  uint32_t head_dim;
  uint32_t page_size;
  uint32_t query_dtype;
  uint32_t logits_dtype;
  uint32_t requested_backend;
} SparkServeQsaScorePlan;

typedef struct SparkServeQsaScoreArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeQsaScorePlan plan;
  // BF16 [batch_size,query_heads,head_dim]. Heads 4..7 are zero padding.
  const void* query;
  // BF16 [pages,page_size,1,head_dim].
  const void* key_cache;
  // INT32 [batch_size,max_pages] and INT32 [batch_size].
  const int32_t* page_table;
  const int32_t* context_lengths;
  // FP32 [batch_size,max_model_len]. Only positions below context length are
  // written; the immediately following top-k stage consumes the same lengths.
  float* logits;
  float score_scale;
  uint32_t reserved;
  void* cuda_stream;
} SparkServeQsaScoreArgs;

typedef struct SparkServeQsaIndexPrepPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t tokens;
  uint32_t groups;
  uint32_t state_slots;
  uint32_t compressed_slots;
  uint32_t num_q_heads;
  uint32_t head_dim;
  uint32_t rotary_dim;
  uint32_t compress_ratio;
  uint32_t num_position_axes;
  uint32_t dtype;
  uint32_t requested_backend;
  uint32_t q_heads_padded;
} SparkServeQsaIndexPrepPlan;

typedef struct SparkServeQsaIndexPrepArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeQsaIndexPrepPlan plan;
  // BF16 [tokens,(num_q_heads+1),head_dim].
  const void* qk;
  // BF16 [tokens,q_heads_padded,head_dim]. Heads >= num_q_heads are zero.
  void* q_output;
  const void* q_norm_weight;
  const void* k_norm_weight;
  // FP32 [cos_sin_rows,rotary_dim].
  const float* cos_sin_cache;
  uint64_t cos_sin_rows;
  const int32_t* axis_map;
  // INT64 [num_position_axes,tokens], with an explicit row stride.
  const int64_t* positions;
  uint64_t positions_stride;
  const int64_t* cache_locs;
  // Persistent BF16 [state_slots,head_dim].
  void* key_state;
  // Persistent INT64 [state_slots,3].
  int64_t* rope_positions;
  // INT32 [groups,compress_ratio] and [groups]. Null when groups == 0.
  const int32_t* group_locs;
  const int32_t* write_locs;
  // Persistent BF16 [compressed_slots,head_dim].
  void* compressed_keys;
  float eps;
  uint32_t reserved;
  void* cuda_stream;
} SparkServeQsaIndexPrepArgs;

typedef struct SparkServeQsaKvPackPlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t batch_size;
  uint32_t slot_capacity;
  uint32_t request_capacity;
  // INT32 elements between rows of req_to_token.
  uint32_t request_stride;
  // Qwen's final QSA selection width: 2048 sparse positions plus three tail
  // positions. Invalid tail entries must follow the valid prefix.
  uint32_t topk;
  // Page-aligned destination stride. For page size 64 and topk 2051 this is
  // 2112 tokens, matching SGLang's TRT-LLM-gen path.
  uint32_t packed_row_stride;
  uint32_t num_kv_heads;
  uint32_t head_dim;
  uint32_t dtype;
  uint32_t requested_backend;
} SparkServeQsaKvPackPlan;

typedef struct SparkServeQsaKvPackArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeQsaKvPackPlan plan;
  // BF16 persistent K/V state: [slot_capacity,num_kv_heads,head_dim].
  const void* key_state;
  const void* value_state;
  // INT32 [request_capacity,request_stride].
  const int32_t* req_to_token;
  // INT32 [batch_size].
  const int32_t* request_indices;
  // INT32 [batch_size,topk]. Valid entries occupy a contiguous prefix.
  const int32_t* logical_indices;
  const int32_t* sequence_lengths;
  // INT32 [batch_size], consumed directly as TRT-LLM-gen seq_lens.
  int32_t* valid_counts;
  // BF16 [batch_size,packed_row_stride,num_kv_heads,head_dim].
  void* packed_key;
  void* packed_value;
  void* cuda_stream;
} SparkServeQsaKvPackArgs;

typedef struct SparkServeQsaDecodePlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t batch_size;
  uint32_t multiprocessor_count;
  uint32_t num_q_heads;
  uint32_t num_kv_heads;
  uint32_t head_dim;
  uint32_t page_size;
  uint32_t pages_per_row;
  uint32_t packed_row_stride;
  uint32_t dtype;
  uint32_t requested_backend;
  uint32_t enable_pdl;
  uint32_t reserved;
} SparkServeQsaDecodePlan;

typedef struct SparkServeQsaDecodeArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeQsaDecodePlan plan;
  // BF16 [batch_size,num_q_heads,head_dim].
  const void* query;
  // BF16 NHD scratch, viewed as
  // [batch_size*pages_per_row,page_size,num_kv_heads,head_dim].
  const void* packed_key;
  const void* packed_value;
  // INT32 [batch_size,pages_per_row] and [batch_size].
  const int32_t* block_tables;
  const int32_t* sequence_lengths;
  // BF16 [batch_size,num_q_heads,head_dim].
  void* output;
  // Zero-initialize once before first use. XQA reserves its first 8 MiB for
  // semaphores and uses the remainder as fixed scratch.
  void* workspace;
  uint64_t workspace_bytes;
  float bmm1_scale;
  float bmm2_scale;
  void* cuda_stream;
} SparkServeQsaDecodeArgs;

typedef struct SparkServeKernelInfo {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t backend;
  uint32_t available;
  uint64_t workspace_bytes;
  const char* name;
  const char* source_revision;
} SparkServeKernelInfo;

// Single-token Gated Delta Network decode. The first native implementation is
// deliberately fixed to the Qwen3.8 Flash shape K=V=128 and BF16 recurrent
// state. Q/K use H heads, V/state use HV heads, and HV must be a multiple of H.
typedef struct SparkServeGdnDecodePlan {
  uint32_t struct_size;
  uint32_t abi_version;
  uint32_t batch_size;
  uint32_t num_qk_heads;
  uint32_t num_value_heads;
  uint32_t key_dim;
  uint32_t value_dim;
  uint32_t state_slots;
  uint32_t state_dtype;
  uint32_t requested_backend;
} SparkServeGdnDecodePlan;

typedef struct SparkServeGdnDecodeArgs {
  uint32_t struct_size;
  uint32_t abi_version;
  SparkServeGdnDecodePlan plan;
  // BF16 Q/K: [B,H,K]. BF16 V: [B,HV,V].
  const void* q;
  const void* k;
  const void* v;
  // BF16 input-dependent gates: [B,HV].
  const void* a;
  const void* b;
  // FP32 persistent gate parameters: [HV].
  const float* a_log;
  const float* dt_bias;
  // BF16 K-contiguous state pool: [slots,HV,V,K], updated in place.
  void* state_pool;
  // INT32 slot per batch row. A negative index produces zero output and no
  // state write. Active rows must name distinct slots within one launch.
  const int32_t* state_indices;
  // BF16 output: [B,HV,V].
  void* output;
  float scale;
  uint32_t reserved;
  void* cuda_stream;
} SparkServeGdnDecodeArgs;

uint32_t sparkserve_kernel_abi_version(void);

SparkServeStatus sparkserve_dense_nvfp4_validate(
    const SparkServeDenseNvfp4Plan* plan);

// Query is safe before model allocation. A valid candidate may be returned
// with available=0 until its external CUDA backend is linked.
SparkServeStatus sparkserve_dense_nvfp4_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeDenseNvfp4Plan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_dense_nvfp4_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeDenseNvfp4Args* args);

SparkServeStatus sparkserve_grouped_nvfp4_validate(
    const SparkServeGroupedNvfp4Plan* plan);

SparkServeStatus sparkserve_grouped_nvfp4_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeGroupedNvfp4Plan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_grouped_nvfp4_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeGroupedNvfp4Args* args);

SparkServeStatus sparkserve_silu_nvfp4_validate(
    const SparkServeSiluNvfp4Plan* plan);

SparkServeStatus sparkserve_silu_nvfp4_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeSiluNvfp4Plan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_silu_nvfp4_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeSiluNvfp4Args* args);

SparkServeStatus sparkserve_segmented_silu_nvfp4_validate(
    const SparkServeSegmentedSiluNvfp4Plan* plan);

SparkServeStatus sparkserve_segmented_silu_nvfp4_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeSegmentedSiluNvfp4Plan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_segmented_silu_nvfp4_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeSegmentedSiluNvfp4Args* args);

SparkServeStatus sparkserve_segmented_nvfp4_quantize_validate(
    const SparkServeSegmentedNvfp4QuantizePlan* plan);

SparkServeStatus sparkserve_segmented_nvfp4_quantize_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeSegmentedNvfp4QuantizePlan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_segmented_nvfp4_quantize_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeSegmentedNvfp4QuantizeArgs* args);

SparkServeStatus sparkserve_moe_route_validate(
    const SparkServeMoeRoutePlan* plan);

SparkServeStatus sparkserve_moe_route_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeMoeRoutePlan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_moe_route_dispatch(
    const SparkServeDeviceCaps* caps,
    const SparkServeMoeRouteArgs* args);

SparkServeStatus sparkserve_moe_route_finalize(
    const SparkServeDeviceCaps* caps,
    const SparkServeMoeRouteArgs* args);

SparkServeStatus sparkserve_ple_gather_validate(
    const SparkServePleGatherPlan* plan);

SparkServeStatus sparkserve_ple_gather_query(
    const SparkServeDeviceCaps* caps,
    const SparkServePleGatherPlan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_ple_gather_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServePleGatherArgs* args);

SparkServeStatus sparkserve_qsa_topk_validate(
    const SparkServeQsaTopkPlan* plan);

SparkServeStatus sparkserve_qsa_topk_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaTopkPlan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_qsa_topk_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaTopkArgs* args);

SparkServeStatus sparkserve_qsa_expand_validate(
    const SparkServeQsaExpandPlan* plan);

SparkServeStatus sparkserve_qsa_expand_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaExpandPlan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_qsa_expand_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaExpandArgs* args);

SparkServeStatus sparkserve_qsa_score_validate(
    const SparkServeQsaScorePlan* plan);

SparkServeStatus sparkserve_qsa_score_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaScorePlan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_qsa_score_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaScoreArgs* args);

SparkServeStatus sparkserve_qsa_index_prep_validate(
    const SparkServeQsaIndexPrepPlan* plan);

SparkServeStatus sparkserve_qsa_index_prep_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaIndexPrepPlan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_qsa_index_prep_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaIndexPrepArgs* args);

SparkServeStatus sparkserve_qsa_kv_pack_validate(
    const SparkServeQsaKvPackPlan* plan);

SparkServeStatus sparkserve_qsa_kv_pack_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaKvPackPlan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_qsa_kv_pack_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaKvPackArgs* args);

SparkServeStatus sparkserve_qsa_decode_validate(
    const SparkServeQsaDecodePlan* plan);

SparkServeStatus sparkserve_qsa_decode_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaDecodePlan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_qsa_decode_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeQsaDecodeArgs* args);

SparkServeStatus sparkserve_gdn_decode_validate(
    const SparkServeGdnDecodePlan* plan);

SparkServeStatus sparkserve_gdn_decode_query(
    const SparkServeDeviceCaps* caps,
    const SparkServeGdnDecodePlan* plan,
    SparkServeKernelInfo* info);

SparkServeStatus sparkserve_gdn_decode_launch(
    const SparkServeDeviceCaps* caps,
    const SparkServeGdnDecodeArgs* args);

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // SPARKSERVE_KERNEL_API_H_
